# Generated by Django 4.1.5 on 2023-01-30 19:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fullname',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('WD', 'Windsor'), ('TO', 'Toronto'), ('CH', 'Chatham'), ('WL', 'WATERLOO')], default='CH', max_length=2),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[(0, 'cancelled'), (1, 'placed_order'), (2, 'shipped_order'), (3, 'deliverd_order')], default='WD', max_length=2)),
                ('date', models.DateTimeField(null=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedBy', to='myapp1.client')),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedItem', to='myapp1.item')),
            ],
        ),
    ]
