# Generated by Django 4.1.5 on 2023-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_client_fullname_client_phone_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
